# Fleet configuration
ssh-user = "keg"
ssh-key-path = "/Users/keg/.ssh/id_rsa"
rsync-options = [
    "-az",             # archive mode, compress
    "--info=progress2", # show progress as a single progress bar
]

# Config values I want to support but haven't implemented yet:
# valid-models = ["modelA", "modelB", "modelC", "modelD", "modelE"]
# robot-states = ["building", "idle", "charging", "broken", "development", "archived"]
