version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: robots
      POSTGRES_USER: robots
      POSTGRES_PASSWORD: robots
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U robots"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 